replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: Always
service:
  internalPort: 3000
  externalPort: 80
ingress:
  enabled: false
  basedomain: 88b6ed8ea2a349f4a049.westeurope.aksapp.io
