# Default values for PHP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  useImagePullSecrets: false
  pullPolicy: IfNotPresent
service:
  externalPort: 80
  internalPort: 3333
ingress:
  enabled: false
  basedomain: 88b6ed8ea2a349f4a049.westeurope.aksapp.io
