# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build-captainkube
    displayName: Build captainkube
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'captainkube/Dockerfile'
        tags: |
          $(tag)
  - job: Build-nodebrady
    displayName: Build nodebrady
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'nodebrady/Dockerfile'
        tags: |
          $(tag)
  - job: Build-parrot
    displayName: Build parrot
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'parrot/Dockerfile'
        tags: |
          $(tag)
  - job: Build-phippy
    displayName: Build phippy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'phippy/Dockerfile'
        tags: |
          $(tag)